### ISSUE TITLE
ABOUT : Introduction and Mission sections

### ISSUE THREAD

**Issue by shiinedev** [dugsiiyeinc/dhaqsoPay#19]
eng waxad soo dhista qeybta hore ee about page ka sectionska ku jira sida About Raveli,Our Values iyo Achievements.

**Comment by A-M-Ahmed** [comment]
The About Us section is not present to explain what Raveli does, its features, or its mission. (Done)

**Comment by A-M-Ahmed** [comment]
The Live Statistics Counters are also missing. These counters should display active users, total downloads, positive feedback, and total transactions. (Done)
