### ISSUE TITLE
Create "Payment Request" Page for dhaqsoPay

### ISSUE THREAD

**Issue by hayle102** [dugsiiyeinc/dhaqsoPay#53]
Design and implement the "Payment Request" page for dhaqsoPay. This page will prompt the user to confirm a payment by entering their PIN and handle errors such as invalid PINs or insufficient balance. A success message will be displayed after a successful payment.

**Tasks**:

1. **Page Design**

**Initial Payment Request**:

- Display a message asking for confirmation, e.g.,
- "Ma hubtaa inaad $100 ku iibsanayso dugsiiye.com? Fadlan gali PIN-kaaga si aad u dhamaystirto."
- Add an input field for entering the PIN.
- Include an "Enter" button for submitting the PIN.

Error Message Design:

**For invalid PINs, display:**

- "PIN galisay ma ahan mid jira."

**For insufficient balance, display:**
- "Waan ka xunnahay, hadhaagaagu kuguma filna."

**Success Confirmation:**

- After a successful payment, display a popup message, e.g.,
- "$100 ayaad u wareejisay 061xxxxxx, Tar: 15/11/24 5:18:38, Haraagaagu waa $500."
- Ensure the design follows the dark mode theme as shown in the reference image.

2. **Functionalities**

**PIN Validation:**

- Check the entered PIN.
- If the PIN is incorrect, display the appropriate error message.

**Balance Validation:**

- Check the user's balance.
- If the balance is insufficient, display the appropriate error message.

**Success Confirmation:**

After successful payment, show the confirmation popup with details such as the amount, transaction time, and remaining balance.
**Additional Notes:**

- Use animations for showing/hiding the error and success popups.
- Match the layout and design with the provided reference image.

**Comment by iftiiin** [comment]
Waxaa ku weydiinaa qofka inuu $100 diri rabo intuu soo galinaa?
